version: 2
updates:
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: daily
