[build]
  publish = "client/dist"
  command = "npm run build"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = ".netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serverless-api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200