FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:22-bookworm

RUN su node -c "npm install -g @tsconfig/node22 @types/express @types/node eslint prettier typescript tsc tsc-watch vite vitest vue-tsc"