version: "3.8"

services:
  application:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:database

  database:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
